const ADDITIONAL_MISSION_ANIMATION_ARCHIVES: Readonly<Record<string, readonly string[]>> = {
  TRSC: ["TRSC", "HUBU"],
  TURR: ["TURR", "BURN", "SMAE", "BUILDNG"],
  REAP: ["REAP", "HUBU"],
  BARR: ["BARR", "HUBU"],
  SARG: ["SARG", "BURN"],
  SCGM: ["SCGM", "BURN"],
  EXPL: ["EXPL", "BURN"],
  ATRIL: ["ATRIL", "ALBU"],
  GRAY: ["GRAY", "ALBU"],
  XENO: ["XENO", "SPAK", "SMAE", "ALBU"],
  SCYT: ["SCYT", "ALBU"],
  ORTU: ["ORTU", "ALBU"],
  SLUG: ["SLUG", "ALBU", "EXPL"],
  EXCOPOD: ["HUBU", "BURN", "PART4"],
  BRRKPOD: ["HUBU", "BURN2", "BURN", "PART4"],
  ROBOPOD: ["HUBU", "BURN2", "BURN", "ROBO"],
  ROBOPOD2: ["HUBU", "BURN2", "BURN", "DROP4"],
  SCNCPOD: ["HUBU", "DROP", "BURN", "PART3"],
  SCNCPOD2: ["HUBU", "BURN", "DROP3"],
  RSCHPOD: ["HUBU", "BURN2", "BURN", "PART2"],
  BIOHIV: ["ALBU", "BLEED", "SAUC"],
  WARHIVE: ["ALBU", "BLEED", "SAUC"],
  BRDRHIV: ["ALBU", "BLEED", "SAUC2"],
  BRDRHIV2: ["ALBU", "BLOO", "BLEED", "SAUC2"],
  MINDHIV: ["ALBU", "SAUC2", "BLEED2", "BLEED"],
  MNDHIV2: ["ALBU", "BLOO", "BLEED2", "SAUC2"],
  RSCHIV: ["BLEED2", "BLEED", "SAUC4"],
  T: ["TURR"],
  XDEPLOY: ["XENO"],
  ENGI: ["ENGI", "BURN"],
  SLOM: ["SLOM", "ALBU"],
  HMINE: ["ENGI"],
  EDPLY: ["EXPL"],
  SDPL: ["SLUG"],
  BEON: ["BEON", "BURN", "GLOT"],
  ZISP: ["ZISP", "GLOT", "ALBU"],
  ONEF: ["LIGHT1F"],
  TWOF: ["LIGHT2F"],
  TEKT: ["TEKT", "TEKTARA"],
  TOXX: ["TOXX", "PORT"],
  SARGSTL: ["SARG"],
  PSYCSTL: ["PSYC"],
  FETU: ["FETU", "WATC"],
  TORT: ["TORT", "WATC"],
  CENT: ["WATC", "CENT"],
  FILL: ["FUEL"],
  TONG: ["TONG", "WATC"],
  SAUC: ["SAWS", "SAUC"],
  BEEK: ["BEAC"],
  CAM: ["CAMM"],
};

export function additionalMissionAnimationArchives(sprite: string): readonly string[] | undefined {
  return Object.hasOwn(ADDITIONAL_MISSION_ANIMATION_ARCHIVES, sprite)
    ? ADDITIONAL_MISSION_ANIMATION_ARCHIVES[sprite] : undefined;
}